numero = int(input('Digite um numero inteiro: '))

print('{:>2} x {:>2} = {:>2}'.format(1, numero, (numero * 1)))
print('{:>2} x {:>2} = {:>2}'.format(2, numero, (numero * 2)))
print('{:>2} x {:>2} = {:>2}'.format(3, numero, (numero * 3)))
print('{:>2} x {:>2} = {:>2}'.format(4, numero, (numero * 4)))
print('{:>2} x {:>2} = {:>2}'.format(5, numero, (numero * 5)))
print('{:>2} x {:>2} = {:>2}'.format(6, numero, (numero * 6)))
print('{:>2} x {:>2} = {:>2}'.format(7, numero, (numero * 7)))
print('{:>2} x {:>2} = {:>2}'.format(8, numero, (numero * 8)))
print('{:>2} x {:>2} = {:>2}'.format(9, numero, (numero * 9)))
print('{:>2} x {:>2} = {:>2}'.format(10, numero, (numero * 10)))
