algoDigitado = input('Digite algo: ')
print('O tipoprimitivo de {} é {}'.format(algoDigitado, type(algoDigitado)))
print('O que foi digitado são letras? {}'.format(algoDigitado.isalpha()))
print('O que foi digitado contém somente espaços? {}'.format(algoDigitado.isspace()))
print('O que foi digitado são letras minusculas? {}'.format(algoDigitado.islower()))
print('O que foi digitado são letras maiusculas? {}'.format(algoDigitado.isupper()))
print('O que foi digitado são numeros? {}'.format(algoDigitado.isnumeric()))
print('O que foi digitado está capitalizado? {}'.format(algoDigitado.istitle()))
print('O que foi digitado é alfanumerico? {}'.format(algoDigitado.isalnum()))
